name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-result
        path: |
          ./bin/Release/
          
    - name: Publish to Github Packages 
      env: # Or as an environment variable
        super_secret: ${{ secrets.PACKAGES }}
      run: dotnet nuget push .\bin\Release\*.nupkg  --api-key $super_secret --source "github" --skip-duplicate